```yaml
project:
  type: website
  output-dir: docs

website:
  title: "Ventura County Wildfire Analysis"

format:
  html:
    theme: cyborg
    toc: false
    code-fold: false
    code-tools: false

execute:
  echo: false
  warning: false
  message: false
```
